//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music
{
    using System;
    using System.Collections.Generic;
    
    public partial class AudioType
    {
        public AudioType()
        {
            this.Audios = new HashSet<Audio>();
        }
    
        public int AudioType_Id { get; set; }
        public string AudioType1 { get; set; }
    
        public virtual ICollection<Audio> Audios { get; set; }
    }
}
