//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainProfile
    {
        public int Profile_Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string ContactNumber { get; set; }
        public string CoverProfilePhoto { get; set; }
        public string FacebookLink { get; set; }
        public string YouTubeLink { get; set; }
        public string TwiterLink { get; set; }
        public string Google_Link { get; set; }
        public string About_1 { get; set; }
        public string Address { get; set; }
    }
}
