//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Music_DBEntities : DbContext
    {
        public Music_DBEntities()
            : base("name=Music_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Audio> Audios { get; set; }
        public virtual DbSet<AudioType> AudioTypes { get; set; }
        public virtual DbSet<PhotoAlbum> PhotoAlbums { get; set; }
        public virtual DbSet<Video> Videos { get; set; }
        public virtual DbSet<VideoType> VideoTypes { get; set; }
        public virtual DbSet<MainProfile> MainProfiles { get; set; }
        public virtual DbSet<PhotoAlbumDetail> PhotoAlbumDetails { get; set; }
    }
}
