//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoAlbumDetail
    {
        public int PhotoAlbumDetail_Id { get; set; }
        public Nullable<int> PhotoAlbum_Id { get; set; }
        public string Photo { get; set; }
    
        public virtual PhotoAlbum PhotoAlbum { get; set; }
    }
}
